### PR TITLE
Change method name: joinGame -> joinRoom & Resolve issue #45

### PR DESCRIPTION
**Pull request by edwardycl**

### CODE REVIEW

**Comment by skystar-p** [comment]
마이너한 change니까 괜찮을듯

**Comment by skystar-p** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit 53a314f has been approved by `skystar-p`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit 53a314f9933a74f2a984a2640c88fbaec06f924a with merge 5480a8f19bbed42f2fe70e3c54ec16053454ffec...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/304291955?utm_source=github_status&utm_medium=notification)
Approved by: skystar-p
Pushing 5480a8f19bbed42f2fe70e3c54ec16053454ffec to master...

**Pull request merged**
