### PR TITLE
Basic Artificial Intelligence

### PR DESCRIPTION
**Pull request by skystar-p**
- [ ] Add and delete feature on room (later!)
- [x] Add test about it

### CODE REVIEW

**Comment by web-mighty-homu** [comment]
:umbrella: The latest upstream changes (presumably #117) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by edwardycl** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit fa0822f has been approved by `edwardycl`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit fa0822f6ab74a09a45d36ba8548d7172d0cc1ed1 with merge d91ba16b7c3e468deaa20b32c0849749b167adb4...

**Comment by web-mighty-homu** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/317979785?utm_source=github_status&utm_medium=notification)

**Comment by tirr-c** [comment]
@web-mighty-homu retry

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit fa0822f6ab74a09a45d36ba8548d7172d0cc1ed1 with merge 1cbc67454e5c2b75abf42501f74cd36abf647aad...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/317984754?utm_source=github_status&utm_medium=notification)
Approved by: edwardycl
Pushing 1cbc67454e5c2b75abf42501f74cd36abf647aad to master...

**Pull request merged**
