### PR TITLE
Fix for AI joker suit in no giruda

### PR DESCRIPTION
**Pull request by skystar-p**

### CODE REVIEW

**Comment by tirr-c** [comment]
Extreme bug.

@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit 1f1b72b has been approved by `tirr-c`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit 1f1b72bcce9c8571b2d75d94bbc26a90050d0003 with merge 468dfe450b384c28185c1cbeb6b53bcea79dcfc7...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/318382778?utm_source=github_status&utm_medium=notification)
Approved by: tirr-c
Pushing 468dfe450b384c28185c1cbeb6b53bcea79dcfc7 to master...

**Pull request merged**
