### PR TITLE
Process turn events

### PR DESCRIPTION
**Pull request by tirr-c**

### CODE REVIEW

**Comment by skystar-p** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit 14492f0 has been approved by `skystar-p`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit 14492f0df7167c058cec8aea23c0f38bb91306a5 with merge 98d49b686002a70ae055086c84156249caeaf96d...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/318100709?utm_source=github_status&utm_medium=notification)
Approved by: skystar-p
Pushing 98d49b686002a70ae055086c84156249caeaf96d to master...

**Pull request merged**
