### PR TITLE
Mailgun setting

### PR DESCRIPTION
**Pull request by skystar-p**

### CODE REVIEW

**Comment by tirr-c** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit ebe3a73 has been approved by `tirr-c`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit ebe3a73ef290b20cac100fef28aae56b962f1830 with merge 4a66c2323d15ac234db5e45e2d53c4764fd8f473...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/317698645?utm_source=github_status&utm_medium=notification)
Approved by: tirr-c
Pushing 4a66c2323d15ac234db5e45e2d53c4764fd8f473 to master...

**Pull request merged**
