### PR TITLE
Bundle MDL, and minor code cleanup

### PR DESCRIPTION
**Pull request by tirr-c**

### CODE REVIEW

**Comment by skystar-p** [comment]
오 번들링...

**Comment by skystar-p** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit 356a1ad has been approved by `skystar-p`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit 356a1ad1da56c6e4608ef339ecdc51dbaf4fe488 with merge cdb02ab27cdcf481ffd8ee485a960e4a9c6739ca...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/317331157?utm_source=github_status&utm_medium=notification)
Approved by: skystar-p
Pushing cdb02ab27cdcf481ffd8ee485a960e4a9c6739ca to master...

**Pull request merged**
