### PR TITLE
View Hall of Fame

### PR DESCRIPTION
**Pull request by tirr-c**

### CODE REVIEW

**Comment by skystar-p** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit d0e2d5b has been approved by `skystar-p`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit d0e2d5b98fbe3676ac9a038738c5b20ada1e1f50 with merge a5efca7b7a4655920cfd1d1c1f495bdee0ba53cd...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/318316191?utm_source=github_status&utm_medium=notification)
Approved by: skystar-p
Pushing a5efca7b7a4655920cfd1d1c1f495bdee0ba53cd to master...

**Pull request merged**
