### PR TITLE
Add devtool that automates e2e test

### PR DESCRIPTION
**Pull request by tirr-c**
`./util/dev-e2e.sh`를 실행하면 E2E 테스트를 실행해 줌

### CODE REVIEW

**Comment by skystar-p** [comment]
굿... 테스트 1개 더 늘었네
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit 758733a has been approved by `skystar-p`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit 758733a0db999efeae1a3bd0fb830583cca67fbb with merge cb38cdd39ccca285689c59850a48f40ace5dba7e...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/308580070?utm_source=github_status&utm_medium=notification)
Approved by: skystar-p
Pushing cb38cdd39ccca285689c59850a48f40ace5dba7e to master...

**Pull request merged**
