### PR TITLE
Various features and fixes

### PR DESCRIPTION
**Pull request by skystar-p**
- Delay when game countinue
- Delay when round end
- Win data (`win`: `ruling` | `opposing`) added
- Restore killed player

### CODE REVIEW

**Comment by tirr-c** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit 05d555a has been approved by `tirr-c`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit 05d555a341b0e881ac6573ab5f3f8983a5cf91d7 with merge e6eeaab560c5231dd749d9ea1eedab5e6dd636f0...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/318152295?utm_source=github_status&utm_medium=notification)
Approved by: tirr-c
Pushing e6eeaab560c5231dd749d9ea1eedab5e6dd636f0 to master...

**Pull request merged**
