### PR TITLE
Implement game continue logic

### PR DESCRIPTION
**Pull request by tirr-c**

### CODE REVIEW

**Comment by skystar-p** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit fe263ae has been approved by `skystar-p`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit fe263ae8eb8b200c0f7164c4fcef3824376244d1 with merge f774455b87e93e1067dc8f9db80ecca2fb2d9d59...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/318299441?utm_source=github_status&utm_medium=notification)
Approved by: skystar-p
Pushing f774455b87e93e1067dc8f9db80ecca2fb2d9d59 to master...

**Pull request merged**
