### PR TITLE
Media file serving for development

### PR DESCRIPTION
**Pull request by skystar-p**

### CODE REVIEW

**Comment by edwardycl** [comment]
commit 내용 적용해도 여전히 avatar 이미지를 못불러온다.

**Comment by skystar-p** [comment]
@edwardycl 엥 그럼 던져주는 url이 잘못된건가.. 나중에 확인해봄

**Comment by tirr-c** [comment]
프록시가 더 필요한가?

**Comment by edwardycl** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit e9dea57 has been approved by `edwardycl`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit e9dea57fadf5a7ebb28514bca3cd5665c6cab19d with merge 2657de68e7cd243fbdd8b52419be58efc0229783...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/309305436?utm_source=github_status&utm_medium=notification)
Approved by: edwardycl
Pushing 2657de68e7cd243fbdd8b52419be58efc0229783 to master...

**Pull request merged**
