### PR TITLE
Hall of fame implementation

### PR DESCRIPTION
**Pull request by skystar-p**
Currently, sorting criteria is only win count.

### CODE REVIEW

**Comment by tirr-c** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit e373977 has been approved by `tirr-c`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit e373977b549ff508b4b059aba030e6d8e8a9ebbe with merge 7772cd18b42f76650035ad229a02d7f4f8b41c27...

**Comment by web-mighty-homu** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/317801438?utm_source=github_status&utm_medium=notification)

**Comment by tirr-c** [comment]
@web-mighty-homu retry

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit e373977b549ff508b4b059aba030e6d8e8a9ebbe with merge 0650022023714c2a4a3d0d6816f8ffb24bfa6c09...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/317804373?utm_source=github_status&utm_medium=notification)
Approved by: tirr-c
Pushing 0650022023714c2a4a3d0d6816f8ffb24bfa6c09 to master...

**Pull request merged**
