### PR TITLE
Add index of Room by room_id

### PR DESCRIPTION
**Pull request by skystar-p**
You need to run `python manage.py migrate`.

### CODE REVIEW

**Comment by tirr-c** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit 48f7e3e has been approved by `tirr-c`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit 48f7e3e568ffd8397df9581aa22e83e037a74cbe with merge 81cdf339d8d1e9ea18306d7919d98efe78dbd934...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/318309969?utm_source=github_status&utm_medium=notification)
Approved by: tirr-c
Pushing 81cdf339d8d1e9ea18306d7919d98efe78dbd934 to master...

**Pull request merged**
