### PR TITLE
Implement account verification view

### PR DESCRIPTION
**Pull request by tirr-c**

### CODE REVIEW

**Comment by skystar-p** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit f4c8d31 has been approved by `skystar-p`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit f4c8d312800ab3f8c5288f3c742a9c5f2affb2f6 with merge 282aac6cc37ba40a0ff4f363cd3d1ef2d4a844b3...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/312237258?utm_source=github_status&utm_medium=notification)
Approved by: skystar-p
Pushing 282aac6cc37ba40a0ff4f363cd3d1ef2d4a844b3 to master...

**Pull request merged**
