### PR TITLE
Add game start feature to frontend

### PR DESCRIPTION
**Pull request by tirr-c**

### CODE REVIEW

**Comment by tirr-c** [comment]
테스트... 살려줘...

**Comment by tirr-c** [comment]
테스트 여기까지만 짜야겠다...

**Comment by skystar-p** [comment]
그래도 테스트 꽤 많고 타입도 아스트랄하게 잘 만들어진듯
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit 4bbd6f3 has been approved by `skystar-p`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit 4bbd6f3e5fc383914f72b05e4be53f144982a744 with merge 6501717ff94d3c0eadda4fbc77322ae4408cde1a...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/317329952?utm_source=github_status&utm_medium=notification)
Approved by: skystar-p
Pushing 6501717ff94d3c0eadda4fbc77322ae4408cde1a to master...

**Pull request merged**
