### PR TITLE
Delay protocol setting and gameplay start behaviour

### PR DESCRIPTION
**Pull request by skystar-p**
- Set Environment variable `$MIGHTY_USE_DELAY=true` to use delay protocol
- You have to run delay server by `python manage.py rundelay` (also runserver)
- `room-start` event now delivers room data
- maybe you have to migrate by `python manage.py migrate`

### CODE REVIEW

**Comment by tirr-c** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit 87f7ccc has been approved by `tirr-c`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit 87f7ccc4c1d76c85e89990fa16ec9c927983cb1d with merge 4a35f28a12e4e1844f5d17bba52cba2b9aceb40a...

**Comment by web-mighty-homu** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/318078630?utm_source=github_status&utm_medium=notification)

**Comment by tirr-c** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit 720d324 has been approved by `tirr-c`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit 720d324b9a05a36b02996385321511649bdcafd7 with merge 76225170207490b3f209e4681804192cc67ef6d5...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/318112517?utm_source=github_status&utm_medium=notification)
Approved by: tirr-c
Pushing 76225170207490b3f209e4681804192cc67ef6d5 to master...

**Pull request merged**
