### PR TITLE
Room GET API now provides total room count

### LINKED ISSUE #38: Room api should provide total number of rooms
For pagination in frontend, /api/room/ GET request must get total number of rooms along with the room list on the page.

### PR DESCRIPTION
**Pull request by skystar-p**
Closes #38 

근데 이거 Pull Request #42 에도 맞게 해야하는데... 이거 먼저 머지하고 42번 풀리퀘도 다시 커밋 넣어야할듯

### CODE REVIEW

**Comment by edwardycl** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit 5b655fc has been approved by `edwardycl`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit 5b655fc43d6f25808427737adb77c25885dc6107 with merge 5b9ba72c7350ed43a1f29f537b75bb7b6b44871f...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/304225737?utm_source=github_status&utm_medium=notification)
Approved by: edwardycl
Pushing 5b9ba72c7350ed43a1f29f537b75bb7b6b44871f to master...

**Pull request merged**
