### PR TITLE
Prevent session duplication

### PR DESCRIPTION
**Pull request by tirr-c**
cc @edwardycl need some CSS for `DuplicateAlertComponent`

### CODE REVIEW

**Comment by web-mighty-homu** [comment]
:umbrella: The latest upstream changes (presumably #88) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by skystar-p** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit c4047ef has been approved by `skystar-p`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit c4047ef5d6c669b0f2845fee84ea9012f660ef44 with merge 33ff66847f3ede5fd1e7936a92ce39afcebe3339...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/311994569?utm_source=github_status&utm_medium=notification)
Approved by: skystar-p
Pushing 33ff66847f3ede5fd1e7936a92ce39afcebe3339 to master...

**Pull request merged**
