### PR TITLE
Verification expiration bug for same email fixed

### PR DESCRIPTION
**Pull request by skystar-p**

### CODE REVIEW

**Comment by edwardycl** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit 8c374e2 has been approved by `edwardycl`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit 8c374e2f058133158950283697363cae01d7daa8 with merge fcc2c217fb0bb3cbac9ac4aa55f6460818a39615...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/317086241?utm_source=github_status&utm_medium=notification)
Approved by: edwardycl
Pushing fcc2c217fb0bb3cbac9ac4aa55f6460818a39615 to master...

**Pull request merged**
