### PR TITLE
Design HallOfFame

### PR DESCRIPTION
**Pull request by edwardycl**

### CODE REVIEW

**Comment by tirr-c** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit b222caa has been approved by `tirr-c`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit b222caa740137348b93593c6ecad1f09d03f2bd2 with merge 4df81d3032aaa87bbaa5d2ba043b0fc11451d89c...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/318402532?utm_source=github_status&utm_medium=notification)
Approved by: tirr-c
Pushing 4df81d3032aaa87bbaa5d2ba043b0fc11451d89c to master...

**Pull request merged**
