### PR TITLE
Add trailing slash to WebSocket URL

### PR DESCRIPTION
**Pull request by tirr-c**

### CODE REVIEW

**Comment by skystar-p** [comment]
ㅋㅋ @web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit 0178c7f has been approved by `skystar-p`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit 0178c7ff87e4cf676e4631b87833d7ff4df65dad with merge e434575fad6e928c87607ec9e348d4db57ec8fd2...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/310484315?utm_source=github_status&utm_medium=notification)
Approved by: skystar-p
Pushing e434575fad6e928c87607ec9e348d4db57ec8fd2 to master...

**Pull request merged**
