### PR TITLE
Fix frontend sign out logic to resolve empty room issue

### PR DESCRIPTION
**Pull request by tirr-c**
Hopefully...

---

* 다른 `Connect` 액션을 받으면 기존 연결을 끊음
* 로그아웃으로 연결이 끊겼을 때 바로 재접속하지 않도록 함

### CODE REVIEW

**Comment by skystar-p** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit 2192bca has been approved by `skystar-p`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit 2192bca0d1229b455214fb4e7dd89a693afb8268 with merge 3c54f917e6accbea463ea27a2749a2cbefd2575f...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/316912299?utm_source=github_status&utm_medium=notification)
Approved by: skystar-p
Pushing 3c54f917e6accbea463ea27a2749a2cbefd2575f to master...

**Pull request merged**
