### PR TITLE
WebSocket Multiplexer skeleton

### PR DESCRIPTION
**Pull request by skystar-p**
- [x] Authentication Check
- [x] Session duplication Check
- [x] Add tests
- [x] Channel routing
- [x] Receive data and multiplex

### CODE REVIEW

**Comment by tirr-c** [comment]
린터 에러...!

**Comment by tirr-c** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit 0e78908 has been approved by `tirr-c`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit 0e789086564573bac2cf1484a0924bc6616fd1be with merge 631cecadb1e036cd4b8e2ba56771ac3b57ee828b...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/307417312?utm_source=github_status&utm_medium=notification)
Approved by: tirr-c
Pushing 631cecadb1e036cd4b8e2ba56771ac3b57ee828b to master...

**Pull request merged**
