### PR TITLE
Enable frontend lint

### LINKED ISSUE #17: Enable linters

### PR DESCRIPTION
**Pull request by tirr-c**
Closes #17.

Why is [`no-shadowed-variable`][no-shadowed-variable] on by default? I don't quite understand.

[no-shadowed-variable]: https://palantir.github.io/tslint/rules/no-shadowed-variable/

### CODE REVIEW

**Comment by skystar-p** [comment]
Maybe not allowing shadowing variable might reduce the confusion, but I think current config is totally okay.

**Comment by tirr-c** [comment]
Maybe it would be okay to set `no-shadowed-variable` as warnings, not errors?

**Comment by skystar-p** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit 78249d7 has been approved by `skystar-p`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit 78249d764ed10e605b2bcf9d94605805fcb59025 with merge c05184b5de312090eefa04fac91f1bcb9c535435...

**Comment by web-mighty-homu** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/300856783?utm_source=github_status&utm_medium=notification)

**Comment by skystar-p** [comment]
@web-mighty-homu retry

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit 78249d764ed10e605b2bcf9d94605805fcb59025 with merge 8c4a2fa28179833f6eb4dc079f26982c18eb407c...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/300857246?utm_source=github_status&utm_medium=notification)
Approved by: skystar-p
Pushing 8c4a2fa28179833f6eb4dc079f26982c18eb407c to master...

**Pull request merged**
