### PR TITLE
Cache TTL and deadlock issue fix

### PR DESCRIPTION
**Pull request by skystar-p**

### CODE REVIEW

**Comment by tirr-c** [comment]
@web-mighty-homu r+ ecdde90

**Comment by web-mighty-homu** [comment]
:scream_cat: `ecdde90` is not a valid commit SHA. Please try again with `772a1f1`.

**Comment by tirr-c** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit 5b253af has been approved by `tirr-c`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit 5b253afcd0df8b8be8c6439a244df3e191bf8462 with merge 5941b42d40153bc3c31266b985fd5c3aedd00456...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/317605818?utm_source=github_status&utm_medium=notification)
Approved by: tirr-c
Pushing 5941b42d40153bc3c31266b985fd5c3aedd00456 to master...

**Pull request merged**
