### PR TITLE
Gameplay hotfix

### PR DESCRIPTION
**Pull request by skystar-p**
- Full bid and final bid bug fix
- Allow president friend and assume to no friend

### CODE REVIEW

**Comment by edwardycl** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit 720997f has been approved by `edwardycl`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit 720997f5ae59054e72c5a2294a59fb7bd42bcaee with merge 10bd7e8c72f1724fbcf0497966a566fe33426155...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/317841633?utm_source=github_status&utm_medium=notification)
Approved by: edwardycl
Pushing 10bd7e8c72f1724fbcf0497966a566fe33426155 to master...

**Pull request merged**
