### PR TITLE
Add bidding feature

### PR DESCRIPTION
**Pull request by tirr-c**
* pass: 출마 포기
* D13: 다이아몬드 13
* N12: 노 기루다 12

등등.

당선된 뒤에도 `bidding` 스테이트이기 때문에 당선 후 공약 부르는 컴포넌트가 사라지지 않는 건 정상임

### CODE REVIEW

**Comment by skystar-p** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit 9931556 has been approved by `skystar-p`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit 99315564438b801cfc7ac9f731af1b0c1950265f with merge 3d3bd7e8c11244e5c2f33d729377352bcf44dd06...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/317600714?utm_source=github_status&utm_medium=notification)
Approved by: skystar-p
Pushing 3d3bd7e8c11244e5c2f33d729377352bcf44dd06 to master...

**Pull request merged**
