### PR TITLE
Update @angular/cli to 1.6.0-rc.0

### PR DESCRIPTION
**Pull request by tirr-c**
Now we won't see the security warning.

### CODE REVIEW

**Comment by skystar-p** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit 59380b0 has been approved by `skystar-p`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit 59380b0e68b5edb79ce75a546cc6e0ceb37d69f0 with merge ba3fded1a7550257658f708e967ec8e09e6f3704...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/308858633?utm_source=github_status&utm_medium=notification)
Approved by: skystar-p
Pushing ba3fded1a7550257658f708e967ec8e09e6f3704 to master...

**Pull request merged**
