### PR TITLE
Add room ready feature

### PR DESCRIPTION
**Pull request by tirr-c**
## TODO

- [x] Add tests

### CODE REVIEW

**Comment by skystar-p** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit d043288 has been approved by `skystar-p`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit d0432882a7d589c5967552bac800d93528c4876a with merge caa6e2c4913905c1e4a20bd4ed3400ae21c3a200...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/316816229?utm_source=github_status&utm_medium=notification)
Approved by: skystar-p
Pushing caa6e2c4913905c1e4a20bd4ed3400ae21c3a200 to master...

**Pull request merged**
