### PR TITLE
`user` field added to response data

### PR DESCRIPTION
**Pull request by skystar-p**
minor fix

### CODE REVIEW

**Comment by edwardycl** [comment]
@web-mighty-homu r+

**Comment by edwardycl** [comment]
@web-mighty-homu r+

**Comment by tirr-c** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit 47ff8b6 has been approved by `tirr-c`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit 47ff8b65b8703e528b0351eac35e0ecbde05a947 with merge ccaa4d0765f064877b05cf2eff5e7d2c1d8300b0...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/303948079?utm_source=github_status&utm_medium=notification)
Approved by: tirr-c
Pushing ccaa4d0765f064877b05cf2eff5e7d2c1d8300b0 to master...

**Pull request merged**
