### PR TITLE
Forbid room join when user is not signed in

### PR DESCRIPTION
**Pull request by tirr-c**

### CODE REVIEW

**Comment by skystar-p** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit 2c33978 has been approved by `skystar-p`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit 2c33978326ec36c865b8abd46a4ebac2aab7d4fe with merge 8fde42b83834253e63bf7559043cbedb241bb40a...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/318388441?utm_source=github_status&utm_medium=notification)
Approved by: skystar-p
Pushing 8fde42b83834253e63bf7559043cbedb241bb40a to master...

**Pull request merged**
