### PR TITLE
Room consumer

### PR DESCRIPTION
**Pull request by skystar-p**
- [x] Room consumers
- [x] Write test

### CODE REVIEW

**Comment by tirr-c** [comment]
`@ensure_csrf_token`하는 부분만 체리픽해서 다른 PR로 넘기면 안 될까?

**Comment by skystar-p** [comment]
ㅇㅋ

**Comment by tirr-c** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit 7896894 has been approved by `tirr-c`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit 78968947e26a7411dc15430ea3f2efcb3f64edff with merge ad4543237c1188e051d141b5523a09f921b5d84a...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/308883332?utm_source=github_status&utm_medium=notification)
Approved by: tirr-c
Pushing ad4543237c1188e051d141b5523a09f921b5d84a to master...

**Pull request merged**
