### PR TITLE
Use shields.io badges for README

### PR DESCRIPTION
**Pull request by tirr-c**

### CODE REVIEW

**Comment by tirr-c** [comment]
@tirr-c r+

**Comment by tirr-c** [comment]
@tirr-c delegate+

**Comment by tirr-c** [comment]
:v: @tirr-c can now approve this pull request

**Comment by tirr-c** [comment]
@tirr-c r+

**Comment by tirr-c** [comment]
@tirr-c try

**Comment by tirr-c** [comment]
:hourglass: Trying commit 2fdbe55246b4520dbc2f064526d7be0b74fa904c with merge a867d83e5d948aa0bf2210ff28b6b331fe36ae53...

**Comment by tirr-c** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/297597364?utm_source=github_status&utm_medium=notification)
State: approved= try=True

**Comment by skystar-p** [comment]
뭔가 Travis는 아직 Unknown으로 뜨는거 같은데 기다려야 하는건가

**Comment by tirr-c** [comment]
아 실수

**Comment by skystar-p** [comment]
@tirr-c r+

**Comment by tirr-c** [comment]
:pushpin: Commit 2b8180d has been approved by `skystar-p`

**Comment by tirr-c** [comment]
:hourglass: Testing commit 2b8180d81affd52060805fb0ed41664177556195 with merge 957bce18b95a7e92969ec930d35568d9b0dbc180...

**Comment by tirr-c** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/297613645?utm_source=github_status&utm_medium=notification)
Approved by: skystar-p
Pushing 957bce18b95a7e92969ec930d35568d9b0dbc180 to master...

**Pull request merged**
