### PR TITLE
Add ensure_csrf_cookie at verify_session

### PR DESCRIPTION
**Pull request by skystar-p**

### CODE REVIEW

**Comment by edwardycl** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit 7e880cb has been approved by `edwardycl`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit 7e880cb881664003e2672a436826085835389145 with merge 6bb14aebd64355218e8ba8f5b2680b443b13f9ab...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/308578366?utm_source=github_status&utm_medium=notification)
Approved by: edwardycl
Pushing 6bb14aebd64355218e8ba8f5b2680b443b13f9ab to master...

**Pull request merged**
