### PR TITLE
AI ghost room fix

### PR DESCRIPTION
**Pull request by skystar-p**

### CODE REVIEW

**Comment by tirr-c** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit 46378e6 has been approved by `tirr-c`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit 46378e6327bf91250007fc767359d289d30df07c with merge dfb9c8bbd73f3c0408a52e60d5943a3b16ab3088...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/318279049?utm_source=github_status&utm_medium=notification)
Approved by: tirr-c
Pushing dfb9c8bbd73f3c0408a52e60d5943a3b16ab3088 to master...

**Comment by skystar-p** [comment]
100th PR merged! :tada:

**Pull request merged**
