### PR TITLE
Add basic sign_up E2E test

### PR DESCRIPTION
**Pull request by tirr-c**

### CODE REVIEW

**Comment by tirr-c** [comment]
@web-mighty-homu try

**Comment by web-mighty-homu** [comment]
:hourglass: Trying commit 63d676a8e8af463645a4d2aab1664e8f22f91780 with merge 54d09f7e1d925f4d9f6e3ba1eabaa0b55a18a56f...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/308783931?utm_source=github_status&utm_medium=notification)
State: approved= try=True

**Comment by tirr-c** [comment]
그냥 머지해도 될 듯

**Pull request merged**
