### PR TITLE
AI addition and deletion in room

### PR DESCRIPTION
**Pull request by skystar-p**

### CODE REVIEW

**Comment by tirr-c** [comment]
😕 이해를 포기했다

@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit 0936f8c has been approved by `tirr-c`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit 0936f8ce53f92774a43dde5a31ee5c3e453d9b57 with merge ece6b3c2bb57759b37d2edac74a909ee10096c4a...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/318203525?utm_source=github_status&utm_medium=notification)
Approved by: tirr-c
Pushing ece6b3c2bb57759b37d2edac74a909ee10096c4a to master...

**Pull request merged**
