### PR TITLE
Frontend result

### PR DESCRIPTION
**Pull request by tirr-c**
* 게임 결과가 뜸!
* 프렌드 공개 이벤트 처리
* SQLite 타임아웃 100으로 늘림 - 딜레이 서버가 계속 DB hit을 한다

### CODE REVIEW

**Comment by skystar-p** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit 7665cb6 has been approved by `skystar-p`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit 7665cb69d90f30ccf0358a170939f12fdb995292 with merge f0c985baeb6d1dd6bf47bf1bc8edfc38414c7c93...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/318265705?utm_source=github_status&utm_medium=notification)
Approved by: skystar-p
Pushing f0c985baeb6d1dd6bf47bf1bc8edfc38414c7c93 to master...

**Pull request merged**
