### PR TITLE
Make no-shadowed-variable lint as warning

### PR DESCRIPTION
**Pull request by tirr-c**

### CODE REVIEW

**Comment by skystar-p** [comment]
생각한대로 warning만 잘 뜨고 에러로 터지지 않는다

**Comment by skystar-p** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit 89e5315 has been approved by `skystar-p`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit 89e53155c1c99967834bb5ac3a1a1fe31eea8808 with merge 07262e9455fae0dc394a42f042e4a286baa8e650...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/300869450?utm_source=github_status&utm_medium=notification)
Approved by: skystar-p
Pushing 07262e9455fae0dc394a42f042e4a286baa8e650 to master...

**Pull request merged**
