### PR TITLE
Event error and reply error is now distinguished

### PR DESCRIPTION
**Pull request by skystar-p**

### CODE REVIEW

**Comment by edwardycl** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit d954711 has been approved by `edwardycl`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit d954711a1519e371ad8af4993bb444fbb1542591 with merge 97b10b23cd3e583a22d18905464bda0edc8bde06...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/307470018?utm_source=github_status&utm_medium=notification)
Approved by: edwardycl
Pushing 97b10b23cd3e583a22d18905464bda0edc8bde06 to master...

**Pull request merged**
