### PR TITLE
Room start and reset abusing fix

### PR DESCRIPTION
**Pull request by skystar-p**
...and null bid issue fixed

### CODE REVIEW

**Comment by edwardycl** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit d14e5ae has been approved by `edwardycl`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit d14e5aeb78127bb870b5886394114ebe30a9fa67 with merge be2fe617eff92ff25fa71de2c50f6a7f34c28ff9...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/317975052?utm_source=github_status&utm_medium=notification)
Approved by: edwardycl
Pushing be2fe617eff92ff25fa71de2c50f6a7f34c28ff9 to master...

**Pull request merged**
