### PR TITLE
Room join and verify session improvement

### PR DESCRIPTION
**Pull request by skystar-p**
`room-join`에서 이미 다른 방에 있으면 일단 오류를 내고 (+ 사소한 문법 오류 수정)

`verify_session`에서는 방에 들어가있으면 room id를 던져줌

### CODE REVIEW

**Comment by web-mighty-homu** [comment]
:umbrella: The latest upstream changes (presumably #79) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by tirr-c** [comment]
@web-mighty-homu rollup

**Comment by tirr-c** [comment]
@web-mighty-homu r=tirr-c

**Comment by web-mighty-homu** [comment]
:pushpin: Commit e14662d has been approved by `tirr-c`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit e14662d3cdede019c8b89acdf696d12822aae57f with merge 2928f141c2b5c9d26dab57f9fe2e581a14ddb43d...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/310777543?utm_source=github_status&utm_medium=notification)
Approved by: tirr-c
Pushing 2928f141c2b5c9d26dab57f9fe2e581a14ddb43d to master...

**Pull request merged**
