### PR TITLE
Add AI add/remove button

### PR DESCRIPTION
**Pull request by tirr-c**

### CODE REVIEW

**Comment by skystar-p** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit 1b71edb has been approved by `skystar-p`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit 1b71edbce4a045901c993967ee4242761cb295e0 with merge eed7d312dd96fca20b14f0f1be3af037a9b6c09d...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/318381024?utm_source=github_status&utm_medium=notification)
Approved by: skystar-p
Pushing eed7d312dd96fca20b14f0f1be3af037a9b6c09d to master...

**Pull request merged**
