### PR TITLE
Now get room options by options object

### PR DESCRIPTION
**Pull request by skystar-p**

### CODE REVIEW

**Comment by skystar-p** [comment]
이거 머지하면 game create할 때 보내는 request 형식도 같이 바꿔줘야 함

**Comment by edwardycl** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit af70f53 has been approved by `edwardycl`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit af70f53581432afdf8e9a900b553bbeadbb3c3c3 with merge bf121b9794b7fc01d489d4588ee20e921a9d088a...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/310032433?utm_source=github_status&utm_medium=notification)
Approved by: edwardycl
Pushing bf121b9794b7fc01d489d4588ee20e921a9d088a to master...

**Pull request merged**
