### PR TITLE
AI bug fix

### PR DESCRIPTION
**Pull request by skystar-p**
- Fix wrong delay at round end
- Fix wrong player count when `room-reset`

### CODE REVIEW

**Comment by tirr-c** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit a9fa0df has been approved by `tirr-c`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit a9fa0dfafabfa4a9da26127cf3581ec245977ced with merge c8b7ada570336c286c8be60f250375ccaf38ecdc...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/318220531?utm_source=github_status&utm_medium=notification)
Approved by: tirr-c
Pushing c8b7ada570336c286c8be60f250375ccaf38ecdc to master...

**Pull request merged**
