### PR TITLE
Frontend president

### PR DESCRIPTION
**Pull request by tirr-c**
Let's vote for this.

### CODE REVIEW

**Comment by skystar-p** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit 13049be has been approved by `skystar-p`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit 13049bead2e552400be076e2c424e83887412e79 with merge 45e815db0e5e5d116561decd4c3dc21c7a76e20c...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/317773095?utm_source=github_status&utm_medium=notification)
Approved by: skystar-p
Pushing 45e815db0e5e5d116561decd4c3dc21c7a76e20c to master...

**Pull request merged**
