### PR TITLE
Refactor kebab-case to snake_case

### PR DESCRIPTION
**Pull request by skystar-p**

### CODE REVIEW

**Comment by tirr-c** [comment]
That's good.

@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit 8ffbf6d has been approved by `tirr-c`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit 8ffbf6d88997df2e0ca54dc625eac1244f43d3b6 with merge 3118e667087c3982efb5c33b7cd7b372088ff4cb...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/317738042?utm_source=github_status&utm_medium=notification)
Approved by: tirr-c
Pushing 3118e667087c3982efb5c33b7cd7b372088ff4cb to master...

**Pull request merged**
