### PR TITLE
Ai room hotfix

### PR DESCRIPTION
**Pull request by skystar-p**

### CODE REVIEW

**Comment by tirr-c** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit 0801464 has been approved by `tirr-c`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit 08014640cca94a492bf0eb89e83bfda2e3e8ca6f with merge 2c138ddcde44034252ddad0987e6275f3ea92791...

**Comment by tirr-c** [comment]
코드 리뷰 이대로 괜찮은가

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/318239178?utm_source=github_status&utm_medium=notification)
Approved by: tirr-c
Pushing 2c138ddcde44034252ddad0987e6275f3ea92791 to master...

**Pull request merged**
