### PR TITLE
Frontend: Refactor WebSocket structures

### PR DESCRIPTION
**Pull request by tirr-c**

### CODE REVIEW

**Comment by skystar-p** [comment]
테스트도 추가됐네 이거 이 커밋으로 PR 끝이지?

**Comment by tirr-c** [comment]
ㅇㅇ 이 정도면 된 것 같음

**Comment by tirr-c** [comment]
앗 잠시만 조금만 더 하겠음

**Comment by tirr-c** [comment]
done

**Comment by skystar-p** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit c43d574 has been approved by `skystar-p`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit c43d5749cb68d9416d83b7d268c54263881c9edb with merge 0c4e67baf563d87d8c745f61ebfde1809d9da345...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/311430397?utm_source=github_status&utm_medium=notification)
Approved by: skystar-p
Pushing 0c4e67baf563d87d8c745f61ebfde1809d9da345 to master...

**Pull request merged**
