### PR TITLE
Room hotfix

### PR DESCRIPTION
**Pull request by skystar-p**
* Room cleanup at startup **(reverted)**
* `room-leave` bug when there is no room but player is in room

### CODE REVIEW

**Comment by tirr-c** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit f43a4bc has been approved by `tirr-c`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit f43a4bc70f7f7f8d60304e7da42cf52421195c45 with merge 99a00ceb7abf11ddf67598c3cb6f38594b4400a7...

**Comment by tirr-c** [comment]
@web-mighty-homu r-

**Comment by web-mighty-homu** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/310770943?utm_source=github_status&utm_medium=notification)

**Comment by tirr-c** [comment]
@web-mighty-homu rollup

**Comment by tirr-c** [comment]
@web-mighty-homu r=tirr-c

**Comment by web-mighty-homu** [comment]
:pushpin: Commit 21cdcd8 has been approved by `tirr-c`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit 21cdcd8ec8a0b5219e5a6f7077c2dbc6561e3f1a with merge f2777dd34d08466df443df5dcfd5573c0ac16752...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/310775969?utm_source=github_status&utm_medium=notification)
Approved by: tirr-c
Pushing f2777dd34d08466df443df5dcfd5573c0ac16752 to master...

**Pull request merged**
