### PR TITLE
Reset User error when navigated

### LINKED ISSUE #36: Navigate using browser does not reset error
location.back()이나 location.forward()가 browser 버튼으로 입력되면 reducer가 알아챌 수 없으니까 url 바뀔때마다 action 던져주게 하면 좋을거 같다.

### PR DESCRIPTION
**Pull request by tirr-c**
Fixes #36.

### CODE REVIEW

**Comment by web-mighty-homu** [comment]
:umbrella: The latest upstream changes (presumably #52) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by skystar-p** [comment]
컴플릭트 났다..

**Comment by skystar-p** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit 7c4ff1a has been approved by `skystar-p`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit 7c4ff1a32ce991fdc7b64b2d0a18ea91582d6a3d with merge a8e7fa99da1603b988457cb0e9e9abc24cf40273...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/307760515?utm_source=github_status&utm_medium=notification)
Approved by: skystar-p
Pushing a8e7fa99da1603b988457cb0e9e9abc24cf40273 to master...

**Pull request merged**
