### PR TITLE
Email duplication is prohibited in sign up

### PR DESCRIPTION
**Pull request by skystar-p**

### CODE REVIEW

**Comment by edwardycl** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit 23f68ae has been approved by `edwardycl`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit 23f68ae4ae8909bad2bc6ba97488f81de94d068b with merge 93c6a744f0e97e287d85e9dcde1551443cf14f94...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/311232746?utm_source=github_status&utm_medium=notification)
Approved by: edwardycl
Pushing 93c6a744f0e97e287d85e9dcde1551443cf14f94 to master...

**Pull request merged**
