### PR TITLE
Document updated for sprint 4

### PR DESCRIPTION
**Pull request by skystar-p**

### CODE REVIEW

**Comment by edwardycl** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit 79232a0 has been approved by `edwardycl`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit 79232a0d7bcce7f09fca2a2f91231003866dffac with merge 3faf2e6f2acb769abf317d6aadd540a112e6d6aa...

**Comment by edwardycl** [comment]
@web-mighty-homu r-

**Comment by web-mighty-homu** [comment]
:pushpin: Commit 79232a0 has been approved by `edwardycl`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit 79232a0d7bcce7f09fca2a2f91231003866dffac with merge 83a9c07b8386bb3b33606299bdff81c9d37aaca8...

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit 79232a0d7bcce7f09fca2a2f91231003866dffac with merge d789a7442463fd8e11231381a86cba3143246c06...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/311198250?utm_source=github_status&utm_medium=notification)
Approved by: edwardycl
Pushing d789a7442463fd8e11231381a86cba3143246c06 to master...

**Pull request merged**
