### PR TITLE
Redirect to lobby if none of the routes match

### PR DESCRIPTION
**Pull request by tirr-c**

### CODE REVIEW

**Comment by skystar-p** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit fd024ec has been approved by `skystar-p`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit fd024ec0b4c83527e52486bc603bd04db853241d with merge bd3163b59393f50e5f0dba60d3ffaab823fe6e60...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/312239229?utm_source=github_status&utm_medium=notification)
Approved by: skystar-p
Pushing bd3163b59393f50e5f0dba60d3ffaab823fe6e60 to master...

**Pull request merged**
