### PR TITLE
Do nothing if the connection is closed due to rejection

### PR DESCRIPTION
**Pull request by tirr-c**
WebSocket close code를 보내서 중복 접속 등이 발생하면 알려줄 수 있음

연결하기도 전에 에러나서 끊겼으면 code를 확인해서 아무 일도 안 하도록 할 수 있다

### CODE REVIEW

**Comment by tirr-c** [comment]
## TODO

- [ ] Write tests

**Comment by skystar-p** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit 8e23845 has been approved by `skystar-p`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit 8e23845146bea67c83927be08e549d09db9039c6 with merge b0e3240da43594e4baf447ef0561ba15013f4089...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/316565640?utm_source=github_status&utm_medium=notification)
Approved by: skystar-p
Pushing b0e3240da43594e4baf447ef0561ba15013f4089 to master...

**Pull request merged**
