### PR TITLE
Fix Giruda selecting

### PR DESCRIPTION
**Pull request by tirr-c**
* 기본으로 스페이드를 고름
* 한 번에 하나만 하이라이트되도록 수정

### CODE REVIEW

**Comment by edwardycl** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit a88b523 has been approved by `edwardycl`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit a88b52378ea8e2ab6acd67c181e211fcb915b531 with merge 3617d12954c51e45e7d0689949d9f886a12b6737...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/318403507?utm_source=github_status&utm_medium=notification)
Approved by: edwardycl
Pushing 3617d12954c51e45e7d0689949d9f886a12b6737 to master...

**Pull request merged**
