### PR TITLE
Django Channels settings and routings

### PR DESCRIPTION
**Pull request by skystar-p**
No routings yet, but this commit will make `./manage.py runserver` behaviour from normal WSGI to ASGI, which is served by Django Channels.

### CODE REVIEW

**Comment by tirr-c** [comment]
Seems trivial.

@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit eded65a has been approved by `tirr-c`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit eded65aa3a869d6bee7d718f7194e9e3e183e067 with merge 3ff2673495a31b846011e45ac26b31097e55b21e...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/300905520?utm_source=github_status&utm_medium=notification)
Approved by: tirr-c
Pushing 3ff2673495a31b846011e45ac26b31097e55b21e to master...

**Pull request merged**
