### PR TITLE
Add favicons and logo

### PR DESCRIPTION
**Pull request by edwardycl**
직접 그리고 favicon generator 사용했음
mstile이 이상하지만 무시하자

### CODE REVIEW

**Comment by skystar-p** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit 35cf5af has been approved by `skystar-p`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit 35cf5af1b09547f46618794a2d517c24c4b499e9 with merge fe9a70d8608d9bcdfba4b7eab8e6253b3e8cf250...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/308393643?utm_source=github_status&utm_medium=notification)
Approved by: skystar-p
Pushing fe9a70d8608d9bcdfba4b7eab8e6253b3e8cf250 to master...

**Pull request merged**
