### PR TITLE
UI Design

### PR DESCRIPTION
**Pull request by edwardycl**
- [ ] Design "Game Room Component"
- [ ] ~~Design "Profile Edit Component"~~
- [x] Design "Verify Account Component"
- [ ] "Hall of Fame" button 위치 수정, 모바일 화면에 표시
- [ ] Game Room, Menu Bar에서 Avatar 불러오기
- [x] Game title 길이가 길어지는 경우 예외처리
- [x] Game Create button for large screen
- [ ] "Game Create Component" popup으로 띄우기 (optional)
- [ ] 모바일 화면에서 Drawer 표시 (optional)

### CODE REVIEW

**Comment by web-mighty-homu** [comment]
:umbrella: The latest upstream changes (presumably #114) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by tirr-c** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit 1dc5c9c has been approved by `tirr-c`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit 1dc5c9c48b4a71fe542cbafb05b7cf1237109366 with merge b8b0e332afb89c967560a92ee0c546ad4e98f79a...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/317939313?utm_source=github_status&utm_medium=notification)
Approved by: tirr-c
Pushing b8b0e332afb89c967560a92ee0c546ad4e98f79a to master...

**Pull request merged**
