### PR TITLE
 Design GameRoomComponent: Bidding

### PR DESCRIPTION
**Pull request by edwardycl**

### CODE REVIEW

**Comment by skystar-p** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit ee47339 has been approved by `skystar-p`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit ee47339a23d4514e63c3e2550de7a93b15b349b3 with merge a3399f58bb7b8addcc5407df62e50b3e987476a9...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/318157384?utm_source=github_status&utm_medium=notification)
Approved by: skystar-p
Pushing a3399f58bb7b8addcc5407df62e50b3e987476a9 to master...

**Pull request merged**
