### PR TITLE
Reset frontend-internal game state when websocket is disconnected

### PR DESCRIPTION
**Pull request by tirr-c**

### CODE REVIEW

**Comment by edwardycl** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit 0ce4ed6 has been approved by `edwardycl`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit 0ce4ed634ce02710cf2e38d47b32760226df6a2a with merge 1fb70a25582111ee1eef9bcb65f48aa3101ed0f0...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/312240212?utm_source=github_status&utm_medium=notification)
Approved by: edwardycl
Pushing 1fb70a25582111ee1eef9bcb65f48aa3101ed0f0 to master...

**Pull request merged**
