### PR TITLE
Gameplay game end data fix

### PR DESCRIPTION
**Pull request by skystar-p**

### CODE REVIEW

**Comment by tirr-c** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit 8d6e7f9 has been approved by `tirr-c`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit 8d6e7f958e40ffddc1a4b9e3084e4a8b0b76f24b with merge 3fbee3f5ab00dcaacd479292425721963085e196...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/318173243?utm_source=github_status&utm_medium=notification)
Approved by: tirr-c
Pushing 3fbee3f5ab00dcaacd479292425721963085e196 to master...

**Pull request merged**
