### PR TITLE
Sprint 3 documents update

### PR DESCRIPTION
**Pull request by skystar-p**

### CODE REVIEW

**Comment by edwardycl** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit 2f549bf has been approved by `edwardycl`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit 2f549bfea9098fc4fe5948e0173f87a34e64b779 with merge d6983865a226aa84caa88e2d5d36112f4d2650f8...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/304592728?utm_source=github_status&utm_medium=notification)
Approved by: edwardycl
Pushing d6983865a226aa84caa88e2d5d36112f4d2650f8 to master...

**Pull request merged**
