### PR TITLE
Cleaning up old images when testing and profile avatar API call

### PR DESCRIPTION
**Pull request by skystar-p**

### CODE REVIEW

**Comment by tirr-c** [comment]
@web-mighty-homu r+

**Comment by web-mighty-homu** [comment]
:pushpin: Commit a4bca08 has been approved by `tirr-c`

**Comment by web-mighty-homu** [comment]
:hourglass: Testing commit a4bca08694291edf83c9984d557e0d733f45f2f5 with merge ba5095129d78c66a8987fa1daaa32563d7c2c326...

**Comment by web-mighty-homu** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/swsnu/swpp17-team2/builds/307085686?utm_source=github_status&utm_medium=notification)
Approved by: tirr-c
Pushing ba5095129d78c66a8987fa1daaa32563d7c2c326 to master...

**Pull request merged**
